### ISSUE TITLE
Implement syntax for multiple return values

### ISSUE THREAD

**Issue by cmxog** [tact-lang/tact-obsolete#11]
```
fn f() -> (T, A) {
 ...
}
```

this would imply a de-structuring assignment to unpack the values:

```
let (a,b) = f();
```

Unless we want to introduce proper tuples (or, perhaps even better, adapt types for that purpose) and optimizations to how they can be passed.

**Comment by p0lunin** [comment]
Closed since decided to use anonymous types such 
```
fn f() -> (type { a: A, b: B }) {
 ...
}
let {a, b} = f();
```
instead of tuples/tensors.
